[Autologin]
Relogin=false
Session=hyprland.desktop
User=

[General]
HaltCommand=/usr/bin/systemctl poweroff
InputMethod=
Numlock=none
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=dotfiles-modern
CursorTheme=Bibata-Modern-Ice
Font=FiraCode Nerd Font,10,-1,5,50,0,0,0,0,0
ThemeDir=/usr/share/sddm/themes

[Users]
DefaultPath=/usr/local/bin:/usr/bin:/bin
HideShells=/usr/bin/nologin,/sbin/nologin
MaximumUid=60513
MinimumUid=1000
RememberLastSession=true
RememberLastUser=true

[Wayland]
EnableHiDPI=true
SessionCommand=/usr/share/sddm/scripts/wayland-session

[X11]
EnableHiDPI=true
ServerArguments=-nolisten tcp
SessionCommand=/usr/share/sddm/scripts/Xsession
