#  _                      _            _    
# | |__  _   _ _ __  _ __| | ___   ___| | __
# | '_ \| | | | '_ \| '__| |/ _ \ / __| |/ /
# | | | | |_| | |_) | |  | | (_) | (__|   < 
# |_| |_|\__, | .__/|_|  |_|\___/ \___|_|\_\
#        |___/|_|                           
#
# --------------------------------------------------

# BACKGROUND
background {
    monitor =
    path = ~/.config/backgrounds/462053.jpg
    blur_passes = 0
    contrast = 0.92
    brightness = 0.72
    vibrancy = 0.25
    vibrancy_darkness = 0.25
}

# GENERAL
general {
    no_fade_in = true
    grace = 0
    disable_loading_bar = false
}

animations {
    enabled = false
}

# Profie-Photo
image {
    monitor =
    path = ~/.config/backgrounds/user-profile.png
    border_size = 3
    border_color = rgba(34, 211, 238, 0.85)
    size = 112
    rounding = -1
    rotate = 0
    reload_time = -1
    reload_cmd = 
    position = 25, 150
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(214, 250, 255, 0.96)
    font_size = 64
    font_family = FiraCode Nerd Font Bold
    position = 30, -8
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(122, 164, 173, 0.92)
    font_size = 19
    font_family = FiraCode Nerd Font Bold
    position = 35, -60
    halign = center
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 320, 55
    color = rgba(8, 36, 43, 0.72)
    rounding = 18
    border_size = 1
    border_color = rgba(34, 211, 238, 0.18)
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)

    position = 34, -190
    halign = center
    valign = center
}

# USER
label {
    monitor = 
    text =   $USER
    color = rgba(214, 250, 255, 0.90)
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 16
    font_family = FiraCode Nerd Font Bold
    position = 38, -190
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 1
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(34, 211, 238, 0.40)
    inner_color = rgba(8, 36, 43, 0.86)
    font_color = rgb(214, 250, 255)
    fade_on_empty = false
    font_family = FiraCode Nerd Font Bold
    placeholder_text = <i><span foreground="##7aa4ad">  Enter Password</span></i>
    hide_input = false
    position = 34, -268
    halign = center
    valign = center
}
