# -------------------------------------------------- 
# Animations
# -------------------------------------------------- 

animations {
    enabled = true
    bezier = smooth, 0.22, 1, 0.36, 1
    bezier = pop, 0.16, 1, 0.3, 1
    bezier = softOut, 0.4, 0, 0.2, 1
    bezier = liner, 1, 1, 1, 1
    animation = windows, 1, 5, smooth, slide
    animation = windowsIn, 1, 5, pop, slide
    animation = windowsOut, 1, 4, softOut, popin 85%
    animation = windowsMove, 1, 4, smooth, slide
    animation = border, 1, 1, liner
    animation = borderangle, 1, 45, liner, loop
    animation = fade, 1, 8, softOut
    animation = workspaces, 1, 5, smooth, slide
}
