# ----------------------------------------------------- 
# General window layout and colors
# ----------------------------------------------------- 

$cyan = 0891b2
$cyan2 = 0e7490
$cyan3 = 155e75
$inactive-color = 08242b


general {
    gaps_in = 5
    gaps_out = 14
    border_size = 2
    col.active_border = rgb($cyan) rgb($cyan2) rgb($cyan3) 45deg
    col.inactive_border = rgb($inactive-color)
    layout = dwindle
    resize_on_border = true
}
